In [1]:
import pandas as pd

In [24]:
komal=pd.read_csv(r"D:\Python\Python for Data Science\StudentsPerformance.csv")

In [25]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77


In [26]:
komal.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75


In [27]:
komal['language score'] = 70

In [28]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70


In [29]:
import numpy as np

In [30]:
language_score = np.arange(0, 1000)

In [32]:
language_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
len(language_score)

1000

In [39]:
komal['language score'] = language_score

In [42]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998


In [55]:
komal = np.random.randint(1, 200, size=1000)

In [59]:
komal

array([ 24, 123, 114, 187, 135,  53, 147,  79, 126,  64, 168, 132,  55,
        95, 115,  10,  36, 107,  43,  58, 152,  23, 135, 185,   9, 117,
        33, 121, 145,  86, 131,   5, 197, 157,  23, 195, 180, 115, 123,
        31, 124,  13,  99, 172,  64, 176, 143, 129, 162,  72,  91, 197,
        14, 104,  74, 145,  73,  35,  28, 155, 155, 162,  85, 100,  50,
         8, 190,  60,  91,   7, 132, 131, 187, 181,  43, 148,  51, 151,
       107,  33,  90, 182,  39,  44,  42,  74,  27,  37, 123, 172,  88,
        34,  22, 156,  68, 162, 148, 192,  88, 163,   6,  77, 191,  37,
        86,  72, 140,  88, 154,  34,  41, 141,  83,  13,  72,   3,  87,
        54,  80,  67,  56, 103,   9,  31,  16, 126,  62, 110, 129,  97,
        88, 136,  46, 104, 154,  79, 101,  19, 113,  33,  96, 122, 160,
       185, 164,  17,  76, 158, 154,  26, 138, 184,  92, 184, 148, 106,
       108, 153,  61,  24, 102, 149,  95, 174, 130, 154, 169, 172, 146,
       198,  60,  38,  72, 142,  71, 183,  35,  94,  27,  73,   

In [60]:
print(min(int_language_score))
print(max(int_language_score))

1
199


In [50]:
komal['language score'] = int_language_score

In [61]:
komal

array([ 24, 123, 114, 187, 135,  53, 147,  79, 126,  64, 168, 132,  55,
        95, 115,  10,  36, 107,  43,  58, 152,  23, 135, 185,   9, 117,
        33, 121, 145,  86, 131,   5, 197, 157,  23, 195, 180, 115, 123,
        31, 124,  13,  99, 172,  64, 176, 143, 129, 162,  72,  91, 197,
        14, 104,  74, 145,  73,  35,  28, 155, 155, 162,  85, 100,  50,
         8, 190,  60,  91,   7, 132, 131, 187, 181,  43, 148,  51, 151,
       107,  33,  90, 182,  39,  44,  42,  74,  27,  37, 123, 172,  88,
        34,  22, 156,  68, 162, 148, 192,  88, 163,   6,  77, 191,  37,
        86,  72, 140,  88, 154,  34,  41, 141,  83,  13,  72,   3,  87,
        54,  80,  67,  56, 103,   9,  31,  16, 126,  62, 110, 129,  97,
        88, 136,  46, 104, 154,  79, 101,  19, 113,  33,  96, 122, 160,
       185, 164,  17,  76, 158, 154,  26, 138, 184,  92, 184, 148, 106,
       108, 153,  61,  24, 102, 149,  95, 174, 130, 154, 169, 172, 146,
       198,  60,  38,  72, 142,  71, 183,  35,  94,  27,  73,   

In [53]:
# create random float numbers between 1 and 100
komal=np.random.uniform(1, 100, size=1000)

In [54]:
komal

array([87.96406188, 50.14702038, 64.73186108, 24.59824755, 28.89295061,
       44.70968959, 18.9469378 ,  7.80862359, 28.13959154, 11.0822862 ,
       28.49717471, 36.03077573, 94.78288216, 92.5701892 , 93.09740714,
       46.97383546, 73.01499932,  6.37171992, 69.96360606, 37.43398287,
       55.85766996, 28.36851509, 75.84222205,  1.26239279, 70.06900763,
       11.84883326,  3.76513257, 44.97441646, 59.51773282, 41.24736311,
       63.18044949, 21.59062067, 54.66745351, 35.17846245,  5.74875596,
       15.51557809, 28.84309748, 58.99708569, 29.59475731, 78.43524286,
       13.203114  , 19.1933851 , 63.4524524 , 78.93285696,  2.46102499,
       23.00529628, 65.41358288, 17.00011546, 12.06411572, 50.82612623,
       69.86781941, 82.26022115, 87.11185384, 13.62581751, 98.69079708,
       65.29901755,  5.00508338, 97.60434234, 12.6942742 , 92.58856084,
       61.73031195, 63.78371768, 85.51606996, 52.4720778 , 46.13197321,
       65.1084123 , 12.43175828, 24.98587831, 89.92185768, 73.86

In [62]:
print(min(komal))
print(max(komal))

1
199
